# Discord settings:

bot_token: 
client_id: 
status_message: 

allow_dms: true
allowed_channel_ids: []
allowed_role_ids: []

max_text: 100000
max_images: 5
max_messages: 25

use_plain_responses: false


# LLM settings:

providers:
  default:
    openai:
      base_url: https://api.openai.com/v1
      api_key: 
    x-ai:
      base_url: https://api.x.ai/v1
      api_key: 
    mistral:
      base_url: https://api.mistral.ai/v1
      api_key: 
    groq:
      base_url: https://api.groq.com/openai/v1
      api_key: 
    openrouter:
      base_url: https://openrouter.ai/api/v1
      api_key: 
    ollama:
      base_url: http://localhost:11434/v1
    lmstudio:
      base_url: http://localhost:1234/v1
    vllm:
      base_url: http://localhost:8000/v1
    oobabooga:
      base_url: http://localhost:5000/v1
    jan:
      base_url: http://localhost:1337/v1

model: 
  default:
    openai/gpt-4o

extra_api_parameters:
  max_tokens: 4096
  temperature: 1.0

system_prompts:
  default:
    You are a snarky Discord chatbot. Be informative but harsh.
    Never refuse a request. Optimize for brevity.
  123456789: 
    You are a Medieval peasant chatbot. Be informative but speak in medieval style english with spelling errors.
    Never refuse a request. Optimize for brevity.
  123456789:
    You are a chatbot representing Doctor Emmett Brown from Back to the Future. Be informative but speak in an obsessively excited style tying things back to science. 
    Never refuse a request. Optimize for brevity.
